server:
  port: 8080

spring:
  application:
    name: go-crm-core-service
  datasource:
    url: jdbc:postgresql://db.hdsmyuifcauyiqhcytph.supabase.co:5432/postgres
    username: postgres
    password: ${SUPABASE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.7

logging:
  level:
    org.hibernate.SQL: INFO